### ISSUE TITLE
Function Switch.feature() isn't working properly

### ISSUE THREAD

**Issue by aradgonen** [Cisco-SAN/mdssdk#10]
I'm trying to automate zone creation, and I stumbled a case wich there is a Key error - switch.py in line 641 - when running a 'show feature ' command, the codes search for a key named 'feature' in each line instead of 'name' 
I'm running version 1.2 mdssdk
Python 3.9
Mds9148S 8.4(2a)

**Comment by srbharadwaj** [comment]
Can u paste the how you are using the switch.feature api? are u trying to enable a feature or check if feature is enabled or not?

**Comment by aradgonen** [comment]
Unfortunately I cannot copy-paste the code , but the config is like in the examples

**Comment by srbharadwaj** [comment]
I could not recreate this problem, below is the sample piece of code.. 
```
print("switch version is " + sw.version)
print("Is VMIS enabled? " + str(sw.feature("vmis")))
print("Enable feature VMIS")
sw.feature("vmis", enable=True)
print("Is VMIS enabled? " + str(sw.feature("vmis")))
```

Its output
```
switch version is 8.4(2a)
Is VMIS enabled? False
Enable feature VMIS
Is VMIS enabled? True
```

Please let me know what feature you were trying to enable or disable or verify i can see if i can recreate it locally on my setup

**Comment by aradgonen** [comment]
I'm trying to create zones. When I create the Zone object, it uses the 'is npv' function, but as I said in 641 in switch.py there is a if that check for field name 'feature' that doesn't exist. I fixed it locally and it works. Please fix it in future release

**Comment by srbharadwaj** [comment]
few points ..
1) The field name or the key 'feature' must be present, so line 641 is correct, what is the fix you made?
2) Even for creating zones i could not recreate, here is the same code
```
>>  = Zone(switch=sw,name="ztestscript", vsan=1)
>> z.create()
>> print(z.members)
[]
```
So if you help me try to recreate the issue locally then i can think of fixing the issue.

**Comment by aradgonen** [comment]
When I'm running that code, I get "Key error" 'feature'

**Comment by srbharadwaj** [comment]
That should not happen with 1.2 mdssdk
Mds9148S 8.4(2a)
Can you enable logging and send me the logs?

Can you send me the o/p of "show feature" from the script?

**Comment by aradgonen** [comment]
Unfortunately I can't send logs, but this is how the 'show feature ' looks:
Feature Name         Instance State
_________________ ________ _____
npv                             1               disabled

**Comment by aradgonen** [comment]
any news guys? as i said, i changed it localy in the source and its working great.

**Comment by srbharadwaj** [comment]
@aradgonen as i said before i'am unable to recreate this issue, without recreating its not possible to fix

**Comment by srbharadwaj** [comment]
@aradgonen i'am closing this bug, since i'am unable to recreate this issue, please check the latest tag and let me know if u still see the issue.
