### ISSUE TITLE
Installation failure Python 3.8 for Windows

### ISSUE THREAD

**Issue by sm1ttynz** [Cisco-SAN/mdssdk#22]
Hi, Having issues trying to install the MDSSDK package, trying to install into Windows Python V3.8.0 VENV.

 error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      in requirements.txt with
      C:\Program Files\Python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'egg_info'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Appreciate any help.

**Comment by srbharadwaj** [comment]
Can you give this a quick try and let me know
```
pip install --upgrade pip
pip install --upgrade setuptools
```

After this please install the package
`pip install mdssdk`

**Comment by sm1ttynz** [comment]
Pip was already at the latest version, but setuptools upgraded. 
Package    Version
---------- -------
pip        22.0.4
setuptools 58.1.0
PS C:\Users\> pip install --upgrade pip
Requirement already satisfied: pip in c:\users\nnnnn\appdata\local\programs\python\python311\lib\site-packages (22.0.4)
PS C:\Users\marksm> pip install --upgrade setuptools
Requirement already satisfied: setuptools in c:\users\nnnnn\appdata\local\programs\python\python311\lib\site-packages (58.1.0)
Collecting setuptools
  Downloading setuptools-61.1.1-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 14.5 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-61.1.1

failed at the same step, seems to be problem with cffi?
Collecting cffi>=1.1
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error


thanks

**Comment by srbharadwaj** [comment]
Not sure, i would suggest just google around for solutions depending on what OS version windows is running or ask the same in stackoverflow.

**Comment by sm1ttynz** [comment]
Okay all good. Thanks for trying.

**Comment by sm1ttynz** [comment]
okay, thanks for taking a look. 

Cheers
