### ISSUE TITLE
How to get list of ports?

### ISSUE THREAD

**Issue by 212850a** [Cisco-SAN/mdssdk#31]
Hi, 
I checked all available classes and could not find any function to get list of available ports on switch. 
Did I miss it somewhere or it's really the case and the only one way to get list of all available ports is to run something like:
`switch_obj.show("show interface status")`

**Comment by srbharadwaj** [comment]
@212850a you can use the ```interfaces``` api
https://github.com/Cisco-SAN/mdssdk/blob/51f0a140e35ca4f120faaf646e39c456de024b4c/mdssdk/utility/switch_utility.py#L80

For some reason document does capture these, you could go over the file
https://github.com/Cisco-SAN/mdssdk/blob/51f0a140e35ca4f120faaf646e39c456de024b4c/mdssdk/utility/switch_utility.py to find the various api's

**Comment by 212850a** [comment]
Many thanks Suhas, this is what I missed - utility directory! :)

**Comment by srbharadwaj** [comment]
if you are good at documentation, can you help fix why it doesn't show up in documentation? :)

**Comment by 212850a** [comment]
> if you are good at documentation, can you help fix why it doesn't show up in documentation? :)

Unfortunately, I'm not. Don't have any experience yet with auto documentation.
