### ISSUE TITLE
Why no environment details available

### ISSUE THREAD

**Issue by 212850a** [Cisco-SAN/mdssdk#32]
It is possible to get details about installed modules, but for some reason no details about (with status) about parts like fans, power supplies. It should be very similar to sw_obj.modules but with a help of "show environment", however it's not there.
It there any obstacles which prevent to add that into module?

**Comment by srbharadwaj** [comment]
ideally this wont come under `sw_obj.modules` as they are not modules per se, they are just different entities like xbar,fans,power supply etc..
We could add more API's like `sw_obj.fan_info`,`sw_obj.ps_info`,`sw_obj.xbar_info` etc..  but they are not as commonly used as `sw_obj.modules`  and hence we didn't add
Also if your sw_obj `connection_type` is 'http' or 'https', you can directly get the json output by simply running the show cmd `sw_obj.show(command="show environment power")`
We could discuss more over email (subharad at cisco dot com) depending on the use case you are trying to solve.

**Comment by 212850a** [comment]
Thanks for reply.
