### ISSUE TITLE
Can this be made to authenticate via ssh_key file?

### ISSUE THREAD

**Issue by wardy3** [Cisco-SAN/mdssdk#9]
netmiko appears to support this via CiscoSSHConnection

but mdssdk classes (eg Switch) don't have it in their __init__

I think this just needs to be passed down to the SSHSession.__init__._cisco_device dict, as its _connect method passes all the items to netmiko's ConnectHandler, yeah?

thanks!

**Comment by srbharadwaj** [comment]
@wardy3 if netmiko supports this then i think mdssdk can also support it as it just leverages netmiko, let me see how well can i integrate it into mdssdk switch class

**Comment by wardy3** [comment]
> @wardy3 if netmiko supports this then i think mdssdk can also support it as it just leverages netmiko, let me see how well can i integrate it into mdssdk switch class

hi. any progress on this? i'm planning on using this module in anger and i need to be able to authenticate passwordless

thanks!

**Comment by srbharadwaj** [comment]
Hi, sorry was not able to look into this as there were other priority issues, can you raise a PR if you know how this works?

**Comment by wardy3** [comment]
Thanks Suhas

I don’t but if I get it working, I will

Thanks ☺

From: Suhas Bharadwaj ***@***.***>
Date: Monday, 23 August 2021 at 14:47
To: Cisco-SAN/mdssdk ***@***.***>
Cc: Wardy ***@***.***>, Mention ***@***.***>
Subject: Re: [Cisco-SAN/mdssdk] Can this be made to authenticate via ssh_key file? (#9)

Hi, sorry was not able to look into this as there were other priority issues, can you raise a PR if you know how this works?

**Comment by wardy3** [comment]
> Hi, sorry was not able to look into this as there were other priority issues, can you raise a PR if you know how this works?

ok, wasn't too hard. but i'm not sure how you want to set up the tests for it. Looks like you have a test switch and a hard-coded password?

**Comment by srbharadwaj** [comment]
> > Hi, sorry was not able to look into this as there were other priority issues, can you raise a PR if you know how this works?
> 
> ok, wasn't too hard. but i'm not sure how you want to set up the tests for it. Looks like you have a test switch and a hard-coded password?

Looked at the code, ya it looks like a simple change.
You can add a unit test case here
`https://github.com/Cisco-SAN/mdssdk/tree/master/tests/test_switch/
`
Or send me a sample script on to use this feature, i can figure out adding a unit test case

**Comment by srbharadwaj** [comment]
Can pick the code from here and see if key_file is working as expected?
https://github.com/srbharadwaj/mdssdk?organization=srbharadwaj&organization=srbharadwaj
